import {useCallback,useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {listarOportunidades,moeda,type Oportunidade} from '../lib/oportunidades'
import {useSessao} from '../lib/sessao'
import {Button,Card,Notice,PageHeader} from '../components/ui'
interface Item {descricao:string;quantidade:number;preco:number}
interface Proposta {id:string;oportunidade_id:string;modelo_id:string|null;titulo:string;texto:string;itens:Item[];subtotais:number[];total:number;numero:string|null;estado:string;validade:string;versao:number;snapshot:{cliente:{nome:string;empresa:string;email:string};empresa:{nome_negocio?:string}}|null}
interface Modelo {id:string;nome:string;texto:string;ativo:boolean}
export default function Propostas(){
 const {gestor}=useSessao(),[lista,setLista]=useState<Proposta[]>([]),[modelos,setModelos]=useState<Modelo[]>([]),[oportunidades,setOportunidades]=useState<Oportunidade[]>([]),[aviso,setAviso]=useState(''),[ocupado,setOcupado]=useState(false)
 const [editor,setEditor]=useState<Proposta|null>(null)
 const [oportunidade,setOportunidade]=useState(''),[modelo,setModelo]=useState(''),[titulo,setTitulo]=useState(''),[texto,setTexto]=useState(''),[validade,setValidade]=useState(''),[itens,setItens]=useState<Item[]>([{descricao:'',quantidade:1,preco:0}]),[nomeModelo,setNomeModelo]=useState('')
 const carregar=useCallback(async()=>{const [p,m,o]=await Promise.all([supabase.from('propostas').select('*').order('criada_em',{ascending:false}).limit(200),supabase.from('proposta_modelos').select('*').order('nome'),listarOportunidades()]);if(p.error||m.error)throw new Error();setLista(p.data??[]);setModelos(m.data??[]);setOportunidades(o.filter(o=>!o.fechado_em&&o.status!=='perdido'))},[])
 useEffect(()=>{void carregar().catch(()=>setAviso('Não foi possível carregar as propostas.'))},[carregar])
 async function executar(acao:()=>PromiseLike<{error:unknown}>){setOcupado(true);setAviso('');try{const r=await acao();if(r.error)throw r.error;await carregar();setAviso('Operação concluída.')}catch{setAviso('Operação recusada. Confira os dados, a validade e atualize a lista.')}finally{setOcupado(false)}}
 async function pdf(p:Proposta){
  const {jsPDF}=await import('jspdf');const {default:autoTable}=await import('jspdf-autotable');const doc=new jsPDF();
  doc.setFontSize(18);doc.text(doc.splitTextToSize(`${p.numero??'Rascunho'} · ${p.titulo}`,180),15,20);doc.setFontSize(10);
  autoTable(doc,{startY:40,body:[['Emitente',p.snapshot?.empresa.nome_negocio??''],['Cliente',p.snapshot?.cliente.nome??''],['Empresa',p.snapshot?.cliente.empresa??''],['Validade',p.validade],['Estado',p.estado]]});
  autoTable(doc,{head:[['Descrição','Quantidade','Preço','Subtotal']],body:p.itens.map((i,n)=>[i.descricao,String(i.quantidade),moeda(i.preco),moeda(p.subtotais[n])]),foot:[['Total','','',moeda(p.total)]],margin:{top:15}});
  autoTable(doc,{body:[[p.texto]],styles:{fontSize:10},margin:{top:15}});doc.save(`proposta-${p.numero??p.id}.pdf`)
 }
 return <div className="page-content"><PageHeader title="Propostas" description="Prepare os itens, confira os termos e emita uma versão com número e conteúdo preservados."/>{aviso&&<Notice>{aviso}</Notice>}
 <Card style={{padding:20,marginBottom:20}}><h2>{editor?'Editar rascunho':'Nova proposta'}</h2><form onSubmit={e=>{e.preventDefault();void executar(()=>supabase.rpc('proposta_salvar',{p_id:editor?.id??null,p_oportunidade:oportunidade,p_titulo:titulo,p_texto:texto,p_itens:itens,p_validade:validade,p_modelo:modelo||null,p_versao:editor?.versao??null}))}} style={{display:'grid',gap:12}}>
 <label>Negociação<select aria-label="Negociação" className="arc-field" required value={oportunidade} onChange={e=>setOportunidade(e.target.value)}><option value="">Selecione</option>{oportunidades.map(o=><option key={o.id} value={o.id}>{o.nome} · {o.contato?.nome}</option>)}</select></label>
 <label>Modelo<select className="arc-field" value={modelo} onChange={e=>{setModelo(e.target.value);setTexto(modelos.find(m=>m.id===e.target.value)?.texto??'')}}><option value="">Sem modelo</option>{modelos.filter(m=>m.ativo).map(m=><option key={m.id} value={m.id}>{m.nome}</option>)}</select></label>
 <label>Título<input className="arc-field" required maxLength={160} value={titulo} onChange={e=>setTitulo(e.target.value)}/></label><label>Validade<input className="arc-field" type="date" required min={new Date().toISOString().slice(0,10)} value={validade} onChange={e=>setValidade(e.target.value)}/></label>
 {itens.map((i,n)=><fieldset key={n} style={{display:'flex',flexWrap:'wrap',gap:12}}><legend>Item {n+1}</legend><label>Descrição<input className="arc-field" required maxLength={500} value={i.descricao} onChange={e=>setItens(a=>a.map((i,j)=>j===n?{...i,descricao:e.target.value}:i))}/></label><label>Quantidade<input className="arc-field" required type="number" min={0.001} max={1000000} step={0.001} value={i.quantidade} onChange={e=>setItens(a=>a.map((i,j)=>j===n?{...i,quantidade:Number(e.target.value)}:i))}/></label><label>Preço (R$)<input className="arc-field" required type="number" min={0} step={0.01} value={i.preco} onChange={e=>setItens(a=>a.map((i,j)=>j===n?{...i,preco:Number(e.target.value)}:i))}/></label><Button type="button" disabled={itens.length===1} onClick={()=>setItens(a=>a.filter((_,j)=>j!==n))}>Remover item</Button></fieldset>)}
 <Button type="button" disabled={itens.length>=100} onClick={()=>setItens(a=>[...a,{descricao:'',quantidade:1,preco:0}])}>Adicionar item</Button><label>Termos e escopo<textarea className="arc-field" maxLength={10000} rows={5} value={texto} onChange={e=>setTexto(e.target.value)}/></label><Button type="submit" disabled={ocupado}>Salvar rascunho</Button>{editor&&<Button type="button" onClick={()=>{setEditor(null);setTitulo('');setTexto('');setItens([{descricao:'',quantidade:1,preco:0}])}}>Novo rascunho</Button>}</form></Card>
 {gestor&&<Card style={{padding:20,marginBottom:20}}><h2>Modelos</h2><p>Salve os termos acima como modelo reutilizável.</p><label>Nome do modelo<input className="arc-field" maxLength={80} value={nomeModelo} onChange={e=>setNomeModelo(e.target.value)}/></label><Button disabled={ocupado||!nomeModelo.trim()} onClick={()=>void executar(()=>supabase.rpc('proposta_modelo_salvar',{p_id:null,p_nome:nomeModelo,p_texto:texto,p_ativo:true}))}>Salvar modelo</Button>{modelos.map(m=><p key={m.id}>{m.nome} · {m.ativo?'Ativo':'Arquivado'} <Button disabled={ocupado} onClick={()=>void executar(()=>supabase.rpc('proposta_modelo_salvar',{p_id:m.id,p_nome:m.nome,p_texto:m.texto,p_ativo:!m.ativo}))}>{m.ativo?'Arquivar':'Ativar'}</Button></p>)}</Card>}
 <Button disabled={ocupado} onClick={()=>void carregar().catch(()=>setAviso('Não foi possível atualizar.'))}>Atualizar lista</Button>{lista.map(p=><Card key={p.id} style={{padding:20,marginTop:12}}><h2>{p.numero??'Rascunho'} · {p.titulo}</h2><p>{moeda(p.total)} · {p.estado} · válido até {p.validade}</p>{p.estado==='rascunho'?<><Button disabled={ocupado} onClick={()=>{setEditor(p);setOportunidade(p.oportunidade_id);setModelo(p.modelo_id??'');setTitulo(p.titulo);setTexto(p.texto);setValidade(p.validade);setItens(p.itens)}}>Editar rascunho</Button> <Button disabled={ocupado} onClick={()=>void executar(()=>supabase.rpc('proposta_emitir',{p_id:p.id,p_versao:p.versao}))}>Emitir proposta</Button></>:<Button onClick={()=>void pdf(p).catch(()=>setAviso('Não foi possível gerar o PDF.'))}>Baixar PDF</Button>}{p.estado==='emitida'&&(['aceita','recusada','cancelada'] as const).map(s=><Button key={s} disabled={ocupado} onClick={()=>void executar(()=>supabase.rpc('proposta_resultado',{p_id:p.id,p_estado:s,p_versao:p.versao}))}>Marcar {s}</Button>)}<p>Aceitar uma proposta não encerra a venda automaticamente. Confira os dados da oportunidade antes de marcar Ganho.</p></Card>)}{!lista.length&&<p>Nenhuma proposta cadastrada.</p>}</div>
}
