import {useCallback,useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {useFunil} from '../lib/funil'
import {useEquipeAtiva} from '../lib/useEquipeAtiva'
import {moduloAtivo} from '../lib/modulos'
import {Button,Card,Notice,PageHeader} from '../components/ui'
type Acao={tipo:string;id?:string;etapa?:string;titulo?:string;texto?:string;instrucao?:string;regra?:string;destino?:string}
interface Regra {id:string;nome:string;ativa:boolean;quando:string;horas:number;condicoes:{etapa?:string};acoes:Acao[];versao:number}
const gatilhos:Record<string,string>={negocio_criado:'Negócio criado',etapa_alterada:'Etapa alterada',dias_na_etapa:'Tempo na mesma etapa',dias_sem_resposta:'Tempo sem mensagem do contato',data:'Data prevista de fechamento',etiqueta_adicionada:'Etiqueta adicionada',mensagem_recebida:'Mensagem recebida',envio_falhou:'Envio falhou',reuniao_criada:'Reunião criada',reuniao_confirmada:'Reunião confirmada',reuniao_remarcada:'Reunião remarcada',reuniao_cancelada:'Reunião cancelada',reuniao_faltou:'Falta à reunião',reuniao_realizada:'Reunião realizada'}
const nomes:Record<string,string>={etiqueta:'Adicionar etiqueta',responsavel:'Definir responsável',mover_negocio:'Mover negócio',criar_negocio:'Criar negócio',tarefa:'Criar tarefa',whatsapp:'Enviar WhatsApp pela uazapi',mensagem_ia:'Gerar e enviar mensagem com IA',followup:'Iniciar follow-up',webhook:'Avisar uma integração'}
export default function Regras(){
 const funil=useFunil(),equipe=useEquipeAtiva(),[lista,setLista]=useState<Regra[]>([]),[etiquetas,setEtiquetas]=useState<{id:string;nome:string}[]>([]),[followups,setFollowups]=useState<{id:string;nome:string}[]>([]),[historico,setHistorico]=useState<{id:string;regra_id:string;estado:string;criado_em:string}[]>([]),[saidas,setSaidas]=useState<{id:string;estado:string;criado_em:string}[]>([])
 const [editor,setEditor]=useState<Regra|null>(null),[nome,setNome]=useState(''),[quando,setQuando]=useState('negocio_criado'),[horas,setHoras]=useState(24),[etapa,setEtapa]=useState(''),[acoes,setAcoes]=useState<Acao[]>([{tipo:'tarefa',titulo:''}]),[aviso,setAviso]=useState(''),[ocupado,setOcupado]=useState(false)
 const carregar=useCallback(async()=>{
  const [r,t,f,h,s]=await Promise.all([supabase.from('gestao_regras').select('*').order('nome'),supabase.from('etiquetas').select('id,nome').order('nome'),moduloAtivo('conversas')?supabase.from('automacao_regras').select('id,nome').eq('tipo','followup'):Promise.resolve({data:[],error:null}),supabase.from('gestao_execucoes').select('id,regra_id,estado,criado_em').order('criado_em',{ascending:false}).limit(100),supabase.from('gestao_saidas').select('id,estado,criado_em').order('criado_em',{ascending:false}).limit(100)])
  if([r,t,f,h,s].some(r=>r.error))throw Error();setLista(r.data??[]);setEtiquetas(t.data??[]);setFollowups(f.data??[]);setHistorico(h.data??[]);setSaidas(s.data??[])
 },[])
 useEffect(()=>{void carregar().catch(()=>setAviso('Não foi possível carregar as regras.'))},[carregar])
 async function guardar(r:Regra|null,ativa:boolean,nomeR=nome,quandoR=quando,horasR=horas,condicoesR:Regra['condicoes']=etapa?{etapa}:{},acoesR=acoes){setOcupado(true);try{const x=await supabase.rpc('gestao_regra_salvar',{p_id:r?.id??null,p_nome:nomeR,p_ativa:ativa,p_quando:quandoR,p_horas:horasR,p_condicoes:condicoesR,p_acoes:acoesR,p_versao:r?.versao??null});if(x.error)throw x.error;await carregar();setEditor(null);setNome('');setAviso('Regra salva. A execução depende do trabalhador da instalação.')}catch{setAviso('Confira a regra e suas ações. A configuração pode ter mudado.')}finally{setOcupado(false)}}
 function editar(r:Regra){setEditor(r);setNome(r.nome);setQuando(r.quando);setHoras(r.horas);setEtapa(r.condicoes.etapa??'');setAcoes(r.acoes)}
 function alterar(n:number,dados:Partial<Acao>){setAcoes(a=>a.map((v,i)=>i===n?{...v,...dados}:v))}
 return <div className="page-content"><PageHeader title="Regras de gestão" description="Quando acontecer um evento, confira uma condição e execute as ações escolhidas."/>{aviso&&<Notice>{aviso}</Notice>}
 <Card style={{padding:20,marginBottom:20}}><h2>{editor?'Editar regra':'Nova regra'}</h2><form style={{display:'grid',gap:14}} onSubmit={e=>{e.preventDefault();void guardar(editor,editor?.ativa??false)}}><label>Nome<input className="arc-field" required maxLength={100} value={nome} onChange={e=>setNome(e.target.value)}/></label>
 <label>Quando<select className="arc-field" value={quando} onChange={e=>setQuando(e.target.value)}>{Object.entries(gatilhos).filter(([k])=>moduloAtivo('conversas')||!['mensagem_recebida','envio_falhou'].includes(k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label>Se a oportunidade estiver na etapa<select className="arc-field" value={etapa} onChange={e=>setEtapa(e.target.value)}><option value="">Qualquer etapa</option>{funil.etapas.map(e=><option key={e.chave} value={e.chave}>{e.rotulo}</option>)}</select></label><p>Eventos de mensagem ou etiqueta não apontam uma oportunidade específica. Para esses eventos, deixe a etapa como “Qualquer etapa”.</p>
 <label>Prazo em horas (espera do gatilho e vencimento das tarefas)<input className="arc-field" required type="number" min={1} max={2160} value={horas} onChange={e=>setHoras(Number(e.target.value))}/></label>
 {acoes.map((a,n)=><fieldset key={n}><legend>Então · ação {n+1}</legend><select aria-label={`Ação ${n+1}`} className="arc-field" value={a.tipo} onChange={e=>setAcoes(v=>v.map((a,i)=>i===n?{tipo:e.target.value}:a))}>{Object.entries(nomes).filter(([k])=>!['whatsapp','mensagem_ia','followup'].includes(k)||moduloAtivo('conversas')&&(k!=='mensagem_ia'||moduloAtivo('assistente'))).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>
 {a.tipo==='etiqueta'&&<label>Etiqueta<select className="arc-field" required value={a.id??''} onChange={e=>alterar(n,{id:e.target.value})}><option value="">Escolha</option>{etiquetas.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</select></label>}
 {a.tipo==='responsavel'&&<label>Pessoa<select className="arc-field" required value={a.id??''} onChange={e=>alterar(n,{id:e.target.value})}><option value="">Escolha</option>{equipe.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</select></label>}
 {a.tipo==='mover_negocio'&&<label>Etapa de destino<select className="arc-field" required value={a.etapa??''} onChange={e=>alterar(n,{etapa:e.target.value})}><option value="">Escolha</option>{funil.abertas.map(t=><option key={t.chave} value={t.chave}>{t.rotulo}</option>)}</select></label>}
 {['tarefa','criar_negocio'].includes(a.tipo)&&<label>Título<input className="arc-field" required maxLength={160} value={a.titulo??''} onChange={e=>alterar(n,{titulo:e.target.value})}/></label>}
 {a.tipo==='whatsapp'&&<label>Mensagem<textarea className="arc-field" required maxLength={1000} value={a.texto??''} onChange={e=>alterar(n,{texto:e.target.value})}/></label>}
 {a.tipo==='mensagem_ia'&&<label>Objetivo da mensagem<textarea className="arc-field" required maxLength={1000} value={a.instrucao??''} onChange={e=>alterar(n,{instrucao:e.target.value})}/></label>}
 {a.tipo==='followup'&&<label>Regra de follow-up<select className="arc-field" required value={a.regra??''} onChange={e=>alterar(n,{regra:e.target.value})}><option value="">Escolha</option>{followups.map(t=><option key={t.id} value={t.id}>{t.nome}</option>)}</select></label>}
 {a.tipo==='webhook'&&<label>Nome da integração configurada<input className="arc-field" required pattern="[a-z][a-z0-9_]{1,39}" value={a.destino??''} onChange={e=>alterar(n,{destino:e.target.value})}/></label>}<Button type="button" disabled={acoes.length===1} onClick={()=>setAcoes(v=>v.filter((_,i)=>i!==n))}>Remover ação</Button></fieldset>)}
 <Button type="button" disabled={acoes.length>=10} onClick={()=>setAcoes(a=>[...a,{tipo:'tarefa',titulo:''}])}>Adicionar ação</Button><Button disabled={ocupado} type="submit">{editor?'Salvar alterações':'Criar regra desativada'}</Button></form></Card>
 <p>Envios exigem autorização do contato e respeitam pedidos de parada. Mensagens diretas usam a uazapi; modelos Meta usam as regras de follow-up. A IA respeita modo de teste, orçamento e passagem para a equipe. Cada regra executa uma vez por cadeia de eventos, com limite de cinco níveis.</p>
 {lista.map(r=><Card key={r.id} style={{padding:20,marginBottom:12}}><h2>{r.nome} · {r.ativa?'Ativa':'Desativada'}</h2><p>{gatilhos[r.quando]} → {r.acoes.map(a=>nomes[a.tipo]).join(', ')}</p><Button disabled={ocupado} onClick={()=>editar(r)}>Editar</Button> <Button disabled={ocupado} onClick={()=>void guardar(r,!r.ativa,r.nome,r.quando,r.horas,r.condicoes,r.acoes)}>{r.ativa?'Desativar':'Ativar'}</Button></Card>)}
 <Card style={{padding:20}}><h2>Execuções recentes</h2><Button disabled={ocupado} onClick={()=>void carregar().catch(()=>setAviso('Não foi possível atualizar.'))}>Atualizar</Button>{historico.map(h=><p key={h.id}>{new Date(h.criado_em).toLocaleString('pt-BR')} · {lista.find(r=>r.id===h.regra_id)?.nome??'Regra'} · {h.estado}</p>)}<h3>Saídas externas</h3>{saidas.map(s=><p key={s.id}>{new Date(s.criado_em).toLocaleString('pt-BR')} · {s.estado}</p>)}<p>Saídas incertas precisam de conferência no provedor antes de qualquer novo envio.</p></Card></div>
}
