import {useCallback,useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {Button,Card,Notice,PageHeader} from '../components/ui'
export default function Seguranca(){
 const [fatores,setFatores]=useState<{id:string;status:string;friendly_name?:string}[]>([]),[novo,setNovo]=useState<{id:string;qr:string;secret:string}|null>(null),[codigo,setCodigo]=useState(''),[aviso,setAviso]=useState(''),[ocupado,setOcupado]=useState(false),[remover,setRemover]=useState<string|null>(null)
 const carregar=useCallback(async()=>{const r=await supabase.auth.mfa.listFactors();if(r.error)throw r.error;setFatores(r.data.all)},[])
 useEffect(()=>{void carregar().catch(()=>setAviso('Não foi possível carregar a segurança da conta.'))},[carregar])
 async function executar(acao:()=>Promise<void>){setOcupado(true);setAviso('');try{await acao();await carregar()}catch{setAviso('Operação recusada. Confira o código e tente novamente.')}finally{setOcupado(false)}}
 async function ativar(){const r=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:`Autenticador ${new Date().toISOString()}`});if(r.error)throw r.error;setNovo({id:r.data.id,qr:r.data.totp.qr_code,secret:r.data.totp.secret})}
 async function verificar(){if(!novo)return;const r=await supabase.auth.mfa.challengeAndVerify({factorId:novo.id,code:codigo});if(r.error)throw r.error;setNovo(null);setCodigo('');setAviso('Autenticador confirmado. Os próximos acessos exigirão o segundo fator.')}
 return <div className="page-content"><PageHeader title="Segurança da conta" description="Proteja o acesso com um aplicativo autenticador."/>{aviso&&<Notice>{aviso}</Notice>}<Card style={{padding:20}}><h2>Verificação em duas etapas</h2>{!novo&&<Button disabled={ocupado} onClick={()=>void executar(ativar)}>Adicionar autenticador</Button>}{novo&&<form onSubmit={e=>{e.preventDefault();void executar(verificar)}}><p>Leia o QR no aplicativo autenticador e confirme o código. Guarde o acesso ao aplicativo para os próximos logins.</p><img src={novo.qr.startsWith('data:')?novo.qr:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(novo.qr)}`} alt="QR para configurar autenticador" width={220}/><p>Chave manual: <code>{novo.secret}</code></p><label>Código de seis dígitos<input className="arc-field" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" required maxLength={6} value={codigo} onChange={e=>setCodigo(e.target.value)}/></label><Button disabled={ocupado} type="submit">Confirmar autenticador</Button> <Button disabled={ocupado} type="button" onClick={()=>void executar(async()=>{const r=await supabase.auth.mfa.unenroll({factorId:novo.id});if(r.error)throw r.error;setNovo(null)})}>Cancelar configuração</Button></form>}
 {fatores.filter(f=>f.id!==novo?.id).map(f=><p key={f.id}>{f.friendly_name??'Autenticador'} · {f.status==='verified'?'Confirmado':'Pendente'} <Button disabled={ocupado} onClick={()=>setRemover(f.id)}>Remover</Button></p>)}{remover&&<Notice tone="warning">Remover este autenticador reduz a proteção do acesso. <Button disabled={ocupado} onClick={()=>void executar(async()=>{const r=await supabase.auth.mfa.unenroll({factorId:remover});if(r.error)throw r.error;await supabase.auth.refreshSession();setRemover(null);setAviso('Autenticador removido.')})}>Confirmar remoção</Button> <Button onClick={()=>setRemover(null)}>Cancelar</Button></Notice>}</Card>
 <Card style={{padding:20,marginTop:20}}><h2>Outras sessões</h2><p>Encerre as outras sessões da sua conta. Tokens já emitidos podem continuar válidos até expirar.</p><Button disabled={ocupado} onClick={()=>void executar(async()=>{const r=await supabase.auth.signOut({scope:'others'});if(r.error)throw r.error;setAviso('Outras sessões encerradas.')})}>Sair nos outros dispositivos</Button></Card></div>
}
