import {useCallback,useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {useFunil} from '../lib/funil'
import type {CampoDef,TipoCampo} from '../lib/camposRegras'
import {Button,Card,Notice} from './ui'
export interface MotivoPerda {chave:string;rotulo:string;exige_retomada:boolean;ativo:boolean;versao:number}
const vazio={chave:'',rotulo:'',entidade:'contato' as CampoDef['entidade'],tipo:'texto' as TipoCampo,opcoes:[] as string[],obrigatorio_em:[] as string[],ativo:true,versao:0}
export default function TabPersonalizacao(){
 const funil=useFunil(),[defs,setDefs]=useState<CampoDef[]>([]),[motivos,setMotivos]=useState<MotivoPerda[]>([]),[campo,setCampo]=useState<CampoDef>(vazio),[opcoes,setOpcoes]=useState(''),[motivo,setMotivo]=useState<MotivoPerda>({chave:'',rotulo:'',exige_retomada:false,ativo:true,versao:0}),[aviso,setAviso]=useState(''),[ocupado,setOcupado]=useState(false)
 const carregar=useCallback(()=>Promise.all([supabase.from('campos_personalizados').select('*').order('rotulo'),supabase.from('motivos_perda').select('*').order('rotulo')]).then(([c,m])=>{if(c.error||m.error){setAviso('Não foi possível carregar a personalização.');return}setDefs(c.data??[]);setMotivos(m.data??[])}),[])
 useEffect(()=>{void carregar()},[carregar])
 async function salvarCampo(e:React.FormEvent){e.preventDefault();setOcupado(true);const r=await supabase.rpc('campo_definir',{p_chave:campo.chave,p_rotulo:campo.rotulo,p_entidade:campo.entidade,p_tipo:campo.tipo,p_opcoes:campo.tipo==='opcao'?opcoes.split('\n').map(o=>o.trim()).filter(Boolean):[],p_etapas:campo.obrigatorio_em,p_ativo:campo.ativo,p_versao:campo.versao||null});setAviso(r.error?r.error.code==='22023'?r.error.message:'Não foi possível salvar o campo.':'Campo salvo.');if(!r.error){setCampo(vazio);setOpcoes('');await carregar()}setOcupado(false)}
 async function salvarMotivo(e:React.FormEvent){e.preventDefault();setOcupado(true);const r=await supabase.rpc('motivo_perda_definir',{p_chave:motivo.chave,p_rotulo:motivo.rotulo,p_retomada:motivo.exige_retomada,p_ativo:motivo.ativo,p_versao:motivo.versao||null});setAviso(r.error?'Não foi possível salvar o motivo. Atualize a configuração.':'Motivo salvo.');if(!r.error){setMotivo({chave:'',rotulo:'',exige_retomada:false,ativo:true,versao:0});await carregar()}setOcupado(false)}
 return <div style={{display:'grid',gap:20}}>{aviso&&<Notice>{aviso}</Notice>}<Card style={{padding:20}}><h2>Campos personalizados</h2><p>Até 50 campos. Tipo, chave e opções são permanentes para preservar dados. Arquivar mantém o histórico e remove exigências futuras. A etapa inicial recebe captação sem exigências. As regras valem ao entrar na etapa ou alterar os campos da oportunidade.</p>
 {defs.map(c=><p key={c.chave}>{c.rotulo} · {c.entidade} · {c.ativo?'Ativo':'Arquivado'} <Button disabled={ocupado} onClick={()=>{setCampo(c);setOpcoes(c.opcoes.join('\n'))}}>Editar campo {c.rotulo}</Button></p>)}
 <form onSubmit={e=>void salvarCampo(e)} style={{display:'grid',gap:12}}>
 <label>Chave do campo<input className="arc-field" required pattern="[a-z][a-z0-9_]{1,39}" disabled={!!campo.versao||ocupado} value={campo.chave} onChange={e=>setCampo({...campo,chave:e.target.value})}/></label>
 <label>Nome do campo<input className="arc-field" required maxLength={80} value={campo.rotulo} onChange={e=>setCampo({...campo,rotulo:e.target.value})}/></label>
 <label>Onde preencher<select aria-label="Onde preencher" className="arc-field" disabled={!!campo.versao} value={campo.entidade} onChange={e=>setCampo({...campo,entidade:e.target.value as CampoDef['entidade']})}><option value="contato">Contato</option><option value="oportunidade">Oportunidade</option></select></label>
 <label>Tipo de campo<select aria-label="Tipo de campo" className="arc-field" disabled={!!campo.versao} value={campo.tipo} onChange={e=>setCampo({...campo,tipo:e.target.value as TipoCampo})}><option value="texto">Texto</option><option value="numero">Número</option><option value="data">Data</option><option value="opcao">Lista de opções</option><option value="booleano">Sim ou não</option></select></label>
 {campo.tipo==='opcao'&&<label>Opções (uma por linha)<textarea className="arc-field" disabled={!!campo.versao} required value={opcoes} onChange={e=>setOpcoes(e.target.value)}/></label>}
 <fieldset><legend>Obrigatório nas etapas</legend>{funil.etapas.filter(e=>e.chave!=='novo_lead').map(e=><label key={e.chave} style={{display:'block'}}><input type="checkbox" checked={campo.obrigatorio_em.includes(e.chave)} onChange={ev=>setCampo({...campo,obrigatorio_em:ev.target.checked?[...campo.obrigatorio_em,e.chave]:campo.obrigatorio_em.filter(x=>x!==e.chave)})}/>{e.rotulo}</label>)}</fieldset>
 <label><input type="checkbox" checked={campo.ativo} onChange={e=>setCampo({...campo,ativo:e.target.checked})}/>Campo ativo</label>
 <div><Button type="submit" disabled={ocupado}>Salvar campo</Button><Button type="button" disabled={ocupado} onClick={()=>{setCampo(vazio);setOpcoes('')}}>Novo campo</Button></div></form></Card>
 <Card style={{padding:20}}><h2>Motivos de perda</h2><p>Renomeie ou arquive motivos sem apagar perdas anteriores. Motivos com retomada exigem uma data ao registrar a perda.</p>
 {motivos.map(m=><p key={m.chave}>{m.rotulo} · {m.ativo?'Ativo':'Arquivado'} <Button disabled={ocupado} onClick={()=>setMotivo(m)}>Editar motivo {m.rotulo}</Button></p>)}
 <form onSubmit={e=>void salvarMotivo(e)} style={{display:'grid',gap:12}}><label>Chave do motivo<input className="arc-field" required pattern="[a-z][a-z0-9_]{1,59}" disabled={!!motivo.versao} value={motivo.chave} onChange={e=>setMotivo({...motivo,chave:e.target.value})}/></label><label>Nome do motivo<input className="arc-field" required maxLength={80} value={motivo.rotulo} onChange={e=>setMotivo({...motivo,rotulo:e.target.value})}/></label><label><input type="checkbox" disabled={motivo.chave==='nao_e_o_momento'} checked={motivo.exige_retomada} onChange={e=>setMotivo({...motivo,exige_retomada:e.target.checked})}/>Exigir data de retomada</label><label><input type="checkbox" checked={motivo.ativo} onChange={e=>setMotivo({...motivo,ativo:e.target.checked})}/>Motivo ativo</label><div><Button type="submit" disabled={ocupado}>Salvar motivo</Button><Button type="button" onClick={()=>setMotivo({chave:'',rotulo:'',exige_retomada:false,ativo:true,versao:0})}>Novo motivo</Button></div></form></Card></div>
}
