DO $$
DECLARE g uuid:=gen_random_uuid(); u uuid:=gen_random_uuid(); f uuid; f2 uuid; c uuid; antigo uuid;
 h text:=repeat('a',64); r jsonb; d jsonb:= '{"nome":"Ana","whatsapp":"5511999900251","utm":{"utm_source":"google","utm_campaign":"outubro","segredo":"fora"}}'; n integer;
BEGIN
 INSERT INTO auth.users(id) VALUES(g),(u);
 UPDATE public.usuarios SET papel='gestor' WHERE id=g;
 UPDATE public.usuarios SET papel='consultor' WHERE id=u;
 PERFORM set_config('request.jwt.claim.sub',u::text,true);
 SET LOCAL ROLE authenticated;
 BEGIN PERFORM public.captacao_criar_fonte('Site',h); RAISE EXCEPTION 'FAIL: consultor criou fonte'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN PERFORM public.captacao_receber(gen_random_uuid(),h,NULL,d); RAISE EXCEPTION 'FAIL: navegador recebeu captação'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',g::text,true);
 SET LOCAL ROLE authenticated;
 f:=public.captacao_criar_fonte('Site',h);
 f2:=public.captacao_criar_fonte('Outro site',h);
 BEGIN PERFORM segredo_hash FROM public.captacao_fontes WHERE id=f; RAISE EXCEPTION 'FAIL: hash exposto'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN UPDATE public.captacao_fontes SET ativa=true WHERE id=f; RAISE EXCEPTION 'FAIL: escrita direta'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub','',true);
 SET LOCAL ROLE service_role;
 r:=public.captacao_receber(f,h,'evt-1',d);
 IF r->>'resultado'<>'nao_autorizado' THEN RAISE EXCEPTION 'FAIL: fonte nasce ligada'; END IF;
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',g::text,true);
 SET LOCAL ROLE authenticated;
 PERFORM public.captacao_configurar_fonte(f,true);
 PERFORM public.captacao_configurar_fonte(f2,true);
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub','',true);
 SET LOCAL ROLE service_role;
 r:=public.captacao_receber(f,repeat('b',64),'evt-1',d);
 IF r->>'resultado'<>'nao_autorizado' THEN RAISE EXCEPTION 'FAIL: segredo errado aceito'; END IF;
 r:=public.captacao_receber(f,h,'evt-1',d);
 IF r->>'resultado'<>'criado' THEN RAISE EXCEPTION 'FAIL: contato não criado: %',r; END IF;
 SELECT id INTO c FROM public.contatos_dados WHERE whatsapp=d->>'whatsapp';
 IF (SELECT count(*) FROM public.oportunidades WHERE contato_id=c)<>1 THEN RAISE EXCEPTION 'FAIL: oportunidade inicial'; END IF;
 r:=public.captacao_receber(f,h,'evt-1',d);
 IF r->>'repetido'<>'true' OR r->>'resultado'<>'criado' THEN RAISE EXCEPTION 'FAIL: reenvio'; END IF;
 SELECT count(*) INTO n FROM public.captacao_recebimentos WHERE fonte_id=f;
 IF n<>1 THEN RAISE EXCEPTION 'FAIL: evento duplicado'; END IF;
 r:=public.captacao_receber(f2,h,'evt-1',jsonb_set(d,'{nome}','"Outro nome"'));
 IF r->>'resultado'<>'existente' THEN RAISE EXCEPTION 'FAIL: repetição entre fontes'; END IF;
 IF (SELECT nome FROM public.contatos_dados WHERE id=c)<>'Ana' THEN RAISE EXCEPTION 'FAIL: sobrescreveu contato'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.contato_atribuicoes WHERE contato_id=c AND fonte_id=f AND utm='{"utm_source":"google","utm_campaign":"outubro"}') THEN RAISE EXCEPTION 'FAIL: primeiro toque'; END IF;
 INSERT INTO public.contatos_dados(whatsapp) VALUES('5511999900252') RETURNING id INTO antigo;
 r:=public.captacao_receber(f,h,NULL,jsonb_set(d,'{whatsapp}','"5511999900252"'));
 IF EXISTS(SELECT 1 FROM public.contato_atribuicoes WHERE contato_id=antigo) THEN RAISE EXCEPTION 'FAIL: atribuiu origem a contato antigo'; END IF;
 r:=public.captacao_receber(f,h,'erro-1','{"whatsapp":"123"}');
 IF r->>'resultado'<>'recusado' OR NOT EXISTS(SELECT 1 FROM public.avisos WHERE tipo='captacao_recusada' AND chave=f::text) THEN RAISE EXCEPTION 'FAIL: recusa sem aviso'; END IF;
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',u::text,true);
 SET LOCAL ROLE authenticated;
 SELECT count(*) INTO n FROM public.captacao_recebimentos;
 IF n<>4 THEN RAISE EXCEPTION 'FAIL: equipe não vê recebimentos %',n; END IF;
 RESET ROLE;
 UPDATE public.usuarios SET ativo=false WHERE id=u;
 SET LOCAL ROLE authenticated;
 SELECT count(*) INTO n FROM public.captacao_recebimentos;
 IF n<>0 THEN RAISE EXCEPTION 'FAIL: desligado ainda lê'; END IF;
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',g::text,true);
 SET LOCAL ROLE authenticated;
 PERFORM public.captacao_configurar_fonte(f,true,repeat('b',64));
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub','',true);
 SET LOCAL ROLE service_role;
 r:=public.captacao_receber(f,h,'novo',d);
 IF r->>'resultado'<>'nao_autorizado' THEN RAISE EXCEPTION 'FAIL: segredo antigo'; END IF;
 INSERT INTO public.captacao_recebimentos(fonte_id,resultado,motivo)
 SELECT f,'recusado','telefone_invalido' FROM generate_series(1,120);
 r:=public.captacao_receber(f,repeat('b',64),'limite',d);
 IF r->>'resultado'<>'limite' THEN RAISE EXCEPTION 'FAIL: limite'; END IF;
 DELETE FROM public.contatos_dados WHERE id=c;
 IF EXISTS(SELECT 1 FROM public.contato_atribuicoes WHERE contato_id=c) OR EXISTS(SELECT 1 FROM public.captacao_recebimentos WHERE contato_id=c) THEN RAISE EXCEPTION 'FAIL: dados órfãos'; END IF;
 RESET ROLE;
END $$;
