DO $$
DECLARE g uuid:=gen_random_uuid(); u uuid:=gen_random_uuid(); f uuid; c uuid; c2 uuid; c3 uuid; r record; n integer;
BEGIN
 INSERT INTO auth.users(id) VALUES(g),(u);
 UPDATE public.usuarios SET papel='gestor' WHERE id=g;
 UPDATE public.usuarios SET papel='consultor' WHERE id=u;
 PERFORM set_config('request.jwt.claim.sub',g::text,true);
 SET LOCAL ROLE authenticated;
 f:=public.captacao_criar_fonte('Landing',repeat('a',64));
 PERFORM public.captacao_configurar_referencia(f,'landing-26','{"utm_source":"google","utm_campaign":"outubro"}');
 PERFORM public.captacao_configurar_fonte(f,true);
 BEGIN PERFORM public.captacao_contato_whatsapp('5511999900261'); RAISE EXCEPTION 'FAIL: navegador cria contato'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 RESET ROLE;
 SET LOCAL ROLE service_role;
 c:=public.captacao_contato_whatsapp('5511999900261','{"canal":"referencia","referencia":"landing-26"}');
 IF NOT EXISTS(SELECT 1 FROM public.contato_atribuicoes WHERE contato_id=c AND canal='referencia' AND fonte_id=f AND utm->>'utm_campaign'='outubro') THEN RAISE EXCEPTION 'FAIL: ref'; END IF;
 c2:=public.captacao_contato_whatsapp('5511999900262','{"canal":"meta","meta":{"source_type":"ad","source_id":"123456","ctwa_clid":"click_26","segredo":"fora"}}');
 IF NOT EXISTS(SELECT 1 FROM public.contato_atribuicoes WHERE contato_id=c2 AND canal='meta' AND meta='{"source_type":"ad","source_id":"123456","ctwa_clid":"click_26"}') THEN RAISE EXCEPTION 'FAIL: Meta'; END IF;
 IF public.captacao_contato_whatsapp('5511999900261','{"canal":"meta","meta":{"source_type":"ad","source_id":"99"}}')<>c THEN RAISE EXCEPTION 'FAIL: reenvio mudou contato'; END IF;
 IF (SELECT canal FROM public.contato_atribuicoes WHERE contato_id=c)<>'referencia' THEN RAISE EXCEPTION 'FAIL: sobrescreveu origem'; END IF;
 c3:=public.captacao_contato_whatsapp('5511999900263',NULL);
 PERFORM public.captacao_contato_whatsapp('5511999900263','{"canal":"referencia","referencia":"landing-26"}');
 IF EXISTS(SELECT 1 FROM public.contato_atribuicoes WHERE contato_id=c3) THEN RAISE EXCEPTION 'FAIL: atribuiu contato antigo'; END IF;
 PERFORM public.captacao_contato_whatsapp('5511999900264','{"canal":"referencia","referencia":"desconhecida"}');
 PERFORM public.captacao_contato_whatsapp('5511999900265','{"canal":"meta","meta":{"source_type":"ad","source_id":"javascript:bad"}}');
 IF (SELECT count(*) FROM public.contato_atribuicoes)<>2 THEN RAISE EXCEPTION 'FAIL: origem inválida'; END IF;
 INSERT INTO public.catalogo_servicos(nome) VALUES('Serviço');
 INSERT INTO public.oportunidades(contato_id,nome) VALUES(c,'Segundo negócio');
 UPDATE public.oportunidades SET status='ganho',valor_proposta=100,servicos_contratados=ARRAY['Serviço'] WHERE contato_id=c;
 RESET ROLE;
 SET LOCAL ROLE authenticated;
 SELECT * INTO r FROM public.captacao_relatorio(now()-interval '1 day',now()+interval '1 day') WHERE canal='referencia';
 IF r.leads IS DISTINCT FROM 1::bigint OR r.ganhos IS DISTINCT FROM 2::bigint OR r.valor_ganho IS DISTINCT FROM 200::numeric THEN RAISE EXCEPTION 'FAIL: relatório multiplica leads %',r; END IF;
 BEGIN PERFORM public.captacao_relatorio(now(),now()-interval '1 day'); RAISE EXCEPTION 'FAIL: intervalo inválido'; EXCEPTION WHEN invalid_parameter_value THEN NULL; END;
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',u::text,true);
 SET LOCAL ROLE authenticated;
 BEGIN PERFORM public.captacao_configurar_referencia(f,'outro','{}'); RAISE EXCEPTION 'FAIL: consultor configura'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 SELECT count(*) INTO n FROM public.captacao_relatorio(now()-interval '1 day',now()+interval '1 day');
 IF n<>3 THEN RAISE EXCEPTION 'FAIL: relatório sem categorias %',n; END IF;
 RESET ROLE;
 SET LOCAL ROLE anon;
 BEGIN PERFORM public.captacao_relatorio(now()-interval '1 day',now()+interval '1 day'); RAISE EXCEPTION 'FAIL: anônimo lê relatório'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN PERFORM nome FROM public.captacao_fontes; RAISE EXCEPTION 'FAIL: anônimo lê fontes'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 RESET ROLE;
 UPDATE public.usuarios SET ativo=false WHERE id=u;
 SET LOCAL ROLE authenticated;
 BEGIN PERFORM public.captacao_relatorio(now()-interval '1 day',now()+interval '1 day'); RAISE EXCEPTION 'FAIL: inativo lê relatório'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',g::text,true);
 SET LOCAL ROLE authenticated;
 BEGIN PERFORM public.captacao_configurar_referencia(f,'ab','{}'); RAISE EXCEPTION 'FAIL: código curto'; EXCEPTION WHEN invalid_parameter_value THEN NULL; END;
 BEGIN PERFORM public.captacao_configurar_referencia(f,'landing-26','{"segredo":"fora"}'); RAISE EXCEPTION 'FAIL: campos desconhecidos na UTM'; EXCEPTION WHEN invalid_parameter_value THEN NULL; END;
 PERFORM public.captacao_configurar_fonte(f,false);
 RESET ROLE;
 SET LOCAL ROLE service_role;
 c3:=public.captacao_contato_whatsapp('5511999900266','{"canal":"referencia","referencia":"landing-26"}');
 IF EXISTS(SELECT 1 FROM public.contato_atribuicoes WHERE contato_id=c3) THEN RAISE EXCEPTION 'FAIL: fonte desligada'; END IF;
 DELETE FROM public.contatos_dados WHERE id=c2;
 IF EXISTS(SELECT 1 FROM public.contato_atribuicoes WHERE contato_id=c2) THEN RAISE EXCEPTION 'FAIL: origem órfã'; END IF;
 RESET ROLE;
END $$;
