DO $$ DECLARE g uuid:=gen_random_uuid();u uuid:=gen_random_uuid();i uuid:=gen_random_uuid();i2 uuid:=gen_random_uuid();r jsonb;c uuid;m uuid; BEGIN
 INSERT INTO auth.users(id) VALUES(g),(u);UPDATE public.usuarios SET papel='gestor' WHERE id=g;UPDATE public.usuarios SET papel='consultor' WHERE id=u;
 PERFORM set_config('request.jwt.claim.sub',u::text,true);SET LOCAL ROLE authenticated;
 BEGIN PERFORM public.assistente_financeiro_salvar(1,'gpt-test',1,2);RAISE EXCEPTION 'FAIL: consultor configura orçamento';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 BEGIN PERFORM public.assistente_consumo_reservar(i,'gpt-test',100,100);RAISE EXCEPTION 'FAIL: navegador reserva';EXCEPTION WHEN insufficient_privilege THEN NULL;END;RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',g::text,true);SET LOCAL ROLE authenticated;
 PERFORM public.assistente_financeiro_salvar(1,'gpt-test',1,2);RESET ROLE;SET LOCAL ROLE service_role;
 r:=public.assistente_consumo_reservar(i,'gpt-test',100000,100000);
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'FAIL: reserva %',r;END IF;
 r:=public.assistente_consumo_reservar(i2,'gpt-test',800000,100000);
 IF r->>'motivo' IS DISTINCT FROM 'teto_mensal' THEN RAISE EXCEPTION 'FAIL: teto %',r;END IF;
 PERFORM public.assistente_consumo_finalizar(i,'{"entrada":10000,"saida":5000}','medido');
 PERFORM public.assistente_consumo_finalizar(i,'{"entrada":99999,"saida":99999}','medido');
 IF (SELECT custo FROM public.assistente_consumo WHERE id=i) IS DISTINCT FROM 0.02::numeric THEN RAISE EXCEPTION 'FAIL: custo/idempotência';END IF;
 r:=public.assistente_consumo_reservar(i2,'gpt-test',1000,1000);
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'FAIL: liberação da reserva';END IF;
 PERFORM public.assistente_consumo_finalizar(i2,NULL,'sem_saldo');
 r:=public.assistente_consumo_reservar(gen_random_uuid(),'gpt-test',1000,1000);
 IF r->>'motivo' IS DISTINCT FROM 'sem_saldo' THEN RAISE EXCEPTION 'FAIL: saldo';END IF;
 RESET ROLE;SET LOCAL ROLE authenticated;PERFORM public.assistente_recarga_confirmar('openai');RESET ROLE;SET LOCAL ROLE service_role;
 r:=public.assistente_consumo_reservar(gen_random_uuid(),'gpt-test',1000,1000);
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'FAIL: recarga';END IF;
 r:=public.assistente_consumo_reservar(gen_random_uuid(),'claude-test',1000,1000);
 IF r->>'motivo' IS DISTINCT FROM 'sem_tarifa' THEN RAISE EXCEPTION 'FAIL: tarifa ausente';END IF;
 INSERT INTO public.contatos_dados(whatsapp) VALUES('5511999900271') RETURNING id INTO c;
 PERFORM public.assistente_encaminhar(c,'Cliente pediu uma pessoa.','pedido_pessoa');
 IF NOT EXISTS(SELECT 1 FROM public.contatos_dados WHERE id=c AND NOT ia_ligada AND ia_encaminhada_motivo='humano' AND ia_resumo='Cliente pediu uma pessoa.') THEN RAISE EXCEPTION 'FAIL: passagem por pessoa';END IF;
 INSERT INTO public.mensagens_whatsapp(contato_id,autor,tipo,conteudo,provedor) VALUES(c,'cliente','texto','Oi','uazapi') RETURNING id INTO m;
 IF NOT public.assistente_resposta_reservar(m,c) OR public.assistente_resposta_reservar(m,c) THEN RAISE EXCEPTION 'FAIL: reserva repetida';END IF;
 UPDATE public.assistente_respostas SET estado='aguardando' WHERE mensagem_id=m;
 IF NOT public.assistente_resposta_reservar(m,c) THEN RAISE EXCEPTION 'FAIL: retomada';END IF;
 UPDATE public.contatos_dados SET ia_encaminhada_motivo='humano',ia_encaminhada_em=now()-interval '1 day' WHERE id=c;
 UPDATE public.assistente_config SET modo='ao_vivo',devolver_apos_minutos=5;
 IF EXISTS(SELECT 1 FROM public.conversas_devolver_ao_assistente() WHERE contato_id=c) THEN RAISE EXCEPTION 'FAIL: volta após pedido humano';END IF;
 RESET ROLE;
END $$;
