DO $$ DECLARE g uuid:=gen_random_uuid();u uuid:=gen_random_uuid();c uuid;o uuid;o2 uuid; BEGIN
 INSERT INTO auth.users(id) VALUES(g),(u);UPDATE public.usuarios SET papel='gestor' WHERE id=g;UPDATE public.usuarios SET papel='consultor' WHERE id=u;
 PERFORM set_config('request.jwt.claim.sub',u::text,true);SET LOCAL ROLE authenticated;
 BEGIN PERFORM public.campo_definir('teste','Teste','contato','texto','{}','{}',true);RAISE EXCEPTION 'FAIL: consultor define';EXCEPTION WHEN insufficient_privilege THEN NULL;END;RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',g::text,true);SET LOCAL ROLE authenticated;
 PERFORM public.campo_definir('orcamento','Orçamento','contato','numero','{}',ARRAY['proposta'],true);
 PERFORM public.campo_definir('aceite','Aceite','oportunidade','booleano','{}',ARRAY['proposta'],true);
 BEGIN PERFORM public.campo_definir('inicial','Inicial','contato','texto','{}',ARRAY['novo_lead'],true);RAISE EXCEPTION 'FAIL: exigência impede captação';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 PERFORM public.campo_definir('opcao','Tipo de projeto','oportunidade','opcao',ARRAY['A','B'],'{}',true);
 PERFORM public.campo_definir('prazo','Prazo','oportunidade','data','{}','{}',true);
 PERFORM public.motivo_perda_definir('concorrente','Escolheu concorrente local',false,true);
 BEGIN PERFORM public.campo_definir('aceite','Alterado','oportunidade','texto','{}','{}',true,1);RAISE EXCEPTION 'FAIL: mudou tipo';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 RESET ROLE;INSERT INTO public.contatos_dados(nome,whatsapp) VALUES('Teste','5511999900301') RETURNING id INTO c;
 SELECT id INTO o FROM public.oportunidades WHERE contato_id=c;
 BEGIN UPDATE public.oportunidades SET status='proposta' WHERE id=o;RAISE EXCEPTION 'FAIL: faltando contato';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 PERFORM set_config('request.jwt.claim.sub',u::text,true);SET LOCAL ROLE authenticated;
 PERFORM public.campos_contato_salvar(c,'{"orcamento":0}',1);
 BEGIN PERFORM public.campos_contato_salvar(c,'{"orcamento":9}',1);RAISE EXCEPTION 'FAIL: versão antiga';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;RESET ROLE;
 BEGIN UPDATE public.oportunidades SET status='proposta' WHERE id=o;RAISE EXCEPTION 'FAIL: faltando negócio';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 UPDATE public.oportunidades SET status='proposta',campos_custom='{"aceite":false,"prazo":"2026-10-05"}' WHERE id=o;
 BEGIN UPDATE public.oportunidades SET campos_custom='{"aceite":false,"prazo":"2026-02-30"}' WHERE id=o;RAISE EXCEPTION 'FAIL: data inválida';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN UPDATE public.oportunidades SET campos_custom='{"desconhecido":"x"}' WHERE id=o;RAISE EXCEPTION 'FAIL: chave desconhecida';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN UPDATE public.oportunidades SET campos_custom='{}' WHERE id=o;RAISE EXCEPTION 'FAIL: apagou obrigatório';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN UPDATE public.oportunidades SET campos_custom=campos_custom||'{"aceite":"false"}' WHERE id=o;RAISE EXCEPTION 'FAIL: booleano inválido';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN UPDATE public.oportunidades SET campos_custom=campos_custom||'{"opcao":"C"}' WHERE id=o;RAISE EXCEPTION 'FAIL: opção inválida';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 UPDATE public.oportunidades SET status='qualificacao' WHERE id=o;
 INSERT INTO public.oportunidades(contato_id,nome,status) VALUES(c,'Segunda oportunidade','qualificacao') RETURNING id INTO o2;
 SET LOCAL ROLE authenticated;
 BEGIN PERFORM public.oportunidades_mover_em_lote(ARRAY[o,o2],'proposta');RAISE EXCEPTION 'FAIL: lote aceitou faltante';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;RESET ROLE;
 IF EXISTS(SELECT 1 FROM public.oportunidades WHERE id=ANY(ARRAY[o,o2]) AND status<>'qualificacao') THEN RAISE EXCEPTION 'FAIL: lote parcial';END IF;
 UPDATE public.oportunidades SET status='perdido',motivo_perda='concorrente' WHERE id=o;
 IF public.rotulo_perda('concorrente')<>'Escolheu concorrente local' THEN RAISE EXCEPTION 'FAIL: rótulo dinâmico';END IF;
 PERFORM set_config('request.jwt.claim.sub',g::text,true);SET LOCAL ROLE authenticated;
 PERFORM public.motivo_perda_definir('concorrente','Concorrente',false,false,1);
 PERFORM public.campo_definir('orcamento','Orçamento','contato','numero','{}',ARRAY['proposta'],false,1);RESET ROLE;
 UPDATE public.oportunidades SET nome='Histórico preservado' WHERE id=o;
 BEGIN UPDATE public.oportunidades SET status='novo_lead' WHERE id=o;UPDATE public.oportunidades SET status='perdido',motivo_perda='concorrente' WHERE id=o;RAISE EXCEPTION 'FAIL: motivo inativo';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN UPDATE public.contatos_dados SET campos_custom='{}' WHERE id=c;RAISE EXCEPTION 'FAIL: removeu arquivado';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN UPDATE public.contatos_dados SET campos_custom='{"orcamento":2}' WHERE id=c;RAISE EXCEPTION 'FAIL: valor arquivado alterado';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 INSERT INTO public.catalogo_servicos(nome,exige_reuniao_previa) VALUES('Serviço personalizado de teste',false);
 UPDATE public.oportunidades SET status='ganho',valor_proposta=1,servicos_contratados=ARRAY['Serviço personalizado de teste'],campos_custom='{"aceite":false}' WHERE id=o2;
 BEGIN UPDATE public.oportunidades SET campos_custom='{"aceite":true}' WHERE id=o2;RAISE EXCEPTION 'FAIL: alterou campo de venda encerrada';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 SET LOCAL ROLE authenticated;PERFORM public.campo_definir('concorrencia','Concorrência','oportunidade','texto','{}',ARRAY['perdido'],true);RESET ROLE;
 UPDATE public.oportunidades SET status='perdido',motivo_cancelamento='Cancelamento solicitado pelo cliente' WHERE id=o2;
 IF NOT EXISTS(SELECT 1 FROM public.oportunidades WHERE id=o2 AND cancelado_em IS NOT NULL AND fechado_em IS NOT NULL) THEN RAISE EXCEPTION 'FAIL: regra de perda bloqueou cancelamento';END IF;
 PERFORM set_config('request.jwt.claim.sub',u::text,true);UPDATE public.usuarios SET ativo=false WHERE id=u;SET LOCAL ROLE authenticated;
 BEGIN UPDATE public.oportunidades SET campos_custom='{"aceite":true}' WHERE id=o2;RAISE EXCEPTION 'FAIL: inativo grava pela tabela';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 IF EXISTS(SELECT 1 FROM public.campos_personalizados) THEN RAISE EXCEPTION 'FAIL: inativo lê';END IF;
 BEGIN PERFORM public.campos_contato_salvar(c,'{}',2);RAISE EXCEPTION 'FAIL: inativo salva';EXCEPTION WHEN insufficient_privilege THEN NULL;END;RESET ROLE;
END $$;
